### ISSUE TITLE
Some Sprites not showing

### ISSUE THREAD

**Issue by Professorlouie** [Dddatt/bss#22]
I downloaded the game to run it locally and it works fully for my friend but for me the sprites of ladybugs, rhino beetles, mantises, and scorpions don't have textures

**Comment by Dddatt** [comment]
nothing is rendering except the stuff like the healthbars? it's a browser issue but shouldn't affect anything.

**Comment by Professorlouie** [comment]
Thanks for the help I am going to close the issue now
