### ISSUE TITLE
i have some questions(NOT A ISSUE JUST SOME QUESTIONS FOR DDATT OR HB PENCIL OR WHOEVER IS  A DEV)

### ISSUE THREAD

**Issue by Hesmyfav** [Dddatt/bss#26]
1. is the game getting update soon, I love it!
2. did you stop using Replit?
3. when killing stump snail are the rewards claimed automatically?
4. how many HB pencil quest are there?

Please reply :>

**Comment by Dddatt** [comment]
1. yuh, expect a beesmas update with the normal beesmas stuff and the major remaining features
2. yes i forgot it exists
3. they scatter in the field similar to coconut crab, since i dont make instantly claimed rewards connect with amulet rewards
4. 5
