### ISSUE TITLE
Add enhancement

### ISSUE THREAD

**Issue by gvnfc3** [Dddatt/bss#6]
Add a saving system which saves your progress.
I recommend looking at a tutorial about localStorage.

**Comment by HB-the-Pencil** [comment]
I believe he's planning to eventually, but for now, he's trying to meet a deadline, and intends to add the most important features first. There are also several bugs that need fixing before release.

(Speaking on behalf of @Dddatt. This message isn't technically endorsed by him, but I'm a lead bugtester so I thought I'd help out :D)

**Comment by Dddatt** [comment]
Yeah. I don't even think I can get around to adding a proper saving system(and also completing the rest of the game) unless I extend the nonsensical deadline. I'll just output and save code of the game's data and be done with it.

**Comment by HB-the-Pencil** [comment]
Saving is done (just so you know) :D
