### ISSUE TITLE
stuff we have yet to do

### ISSUE THREAD

**Issue by HB-the-Pencil** [Dddatt/bss#8]
NPCs
rework most of the dialogue
shops
bosses
gates

_Originally posted by @ttaddD in https://github.com/Dddatt/bss/discussions/2#discussioncomment-5652824_

**Comment by HB-the-Pencil** [comment]
Wait commando chick is already in the game though right?

Also stickbug wouldn't bee too hard, you just have to make like a stick-y guy right lol

he's just a bunch of rotated boxes? idk I'll look up a video

**Comment by HB-the-Pencil** [comment]
It's so weird to watch videos of the real bss it's like this one with shaders o.O

**Comment by HB-the-Pencil** [comment]
Ohhhh my bad

got it

what if you still added a mini stickbug on a wall? for the meme? and also so that the translator is still usable

**Comment by Dddatt** [comment]
Yeah I'll just add a stickbug figure and give like 150 tickets for using the translator on him since he's now mentally ill

**Comment by HB-the-Pencil** [comment]
that's not very nice to the poor bug ;-;

I have the translator program on Khan if you need it lol

**Comment by HB-the-Pencil** [comment]
also I managed to clip under stump from this area

![image](https://user-images.githubusercontent.com/118207101/235173889-bd13c03d-f4ab-4fdb-b262-a59182dbaf23.png)

there's a spot where you can fall between the triangles bc they're only there for decoration

**Comment by HB-the-Pencil** [comment]
uhhhh then my glider broke

![image](https://user-images.githubusercontent.com/118207101/235174407-e0016e5b-7ed6-4f69-bd14-85e0a6270a82.png)

Interesting

**Comment by Dddatt** [comment]
Yeah after I fixed a jumping bug the glider started glitching sooo.....ig I'll revert it cuz it's too common

There was also a similar stump glitch a while ago. I fixed or shrunk the holes but I can't get it to match perfectly with the shape. But that means more usage for the soon to be added reset character button!!

**Comment by HB-the-Pencil** [comment]
Yayy character reset

ughhhh im spreading myself so thin with school and golf and coding and so much other stuff ;-;

**Comment by HB-the-Pencil** [comment]
Wait what was the jumping bug? Was it the super high jump when in the ground thing?

**Comment by Dddatt** [comment]
And I'm getting bored with this game lol

Starting to lose motivation but I'll eventually get it done and then enjoy my summer and stuff

I should be free today and some of the weekend so I guess I'll start making progress

**Comment by HB-the-Pencil** [comment]
Interesting

yeah I've kinda found a glitch where you can double jump by strafing into walls sometimes. It's kinda weird

**Comment by Dddatt** [comment]
wait wait I've already started to work so idk if there will be merge conflicts and stuff I see later

**Comment by HB-the-Pencil** [comment]
There shouldn't be it says it can be merged with no conflicts (again, just squash and merge it)

**Comment by Dddatt** [comment]
What I'm so confused didn't you say not to merge it because it'll add like 40 commits?

I already c&p'ed the code in and then had to rush and save the stuff I was working on then left cuz I had idk how many hrs left

Ig I'll somehow make some progress on other things while I wait for the thingie to reset

**Comment by Dddatt** [comment]
Update: I've now temporarily moved to Replit to continue working on the game...Doesn't seem to be very reliable though :( 
![image](https://user-images.githubusercontent.com/115298848/235212908-d0415696-88c5-4ad2-92ee-d5e9322b16aa.png)

everything is so slow and laggy...

**Comment by HB-the-Pencil** [comment]
why did you censor "c&p'ed"? ohhhh *c*opy & *p*asted got it I thought you were censoring copied

Yeah I had replit but got banned for a dum comment I don't even know what so I deleted account, github is a lot better lol

I think you can copy the files to a workspace in visual studio and just work on it there, then copy it over to github... or just pay like the 12 bucks for unlimited codespace......

**Comment by HB-the-Pencil** [comment]
wow it's cheaper than I thought lol

![image](https://user-images.githubusercontent.com/118207101/235232692-b5a9dc40-4c14-4a03-bfd1-3836a3a9b103.png)

**Comment by Dddatt** [comment]
Yeah I'm gonna just download the files, edit them, then paste them into GitHub. Replit is weird and slow

**Comment by HB-the-Pencil** [comment]
![image](https://user-images.githubusercontent.com/118207101/235448874-aa0c86cd-5203-4ea8-9d74-5160cfd17225.png)

hmmm how'd this happen???

(answer: i left it open in the background lol)

**Comment by Dddatt** [comment]
Lol I've never even used up 1GB of storage before
